<?php
/**
 * Product Display Block Class
 *
 * @package Preview_And_Tools_For_Makeshop_WP_Option
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

/**
 * Class for registering and rendering the product display block.
 */
class TFMWP_Block_Product_Display {

	/**
	 * Initialize the block.
	 */
	public static function init() {
		add_action( 'init', array( __CLASS__, 'register_block' ) );
		add_action( 'rest_api_init', array( __CLASS__, 'register_rest_routes' ) );
	}

	/**
	 * Register REST API routes.
	 */
	public static function register_rest_routes() {
		register_rest_route(
			'tfmwp/v1',
			'/fetch-products',
			array(
				'methods'             => 'POST',
				'callback'            => array( __CLASS__, 'rest_fetch_products' ),
				'permission_callback' => function () {
					return current_user_can( 'edit_posts' );
				},
				'args'                => array(
					'urls' => array(
						'required'          => true,
						'type'              => 'array',
						'sanitize_callback' => function( $urls ) {
							return array_map( 'esc_url_raw', $urls );
						},
					),
				),
			)
		);
	}

	/**
	 * REST API callback to fetch products.
	 *
	 * @param WP_REST_Request $request The request object.
	 * @return WP_REST_Response|WP_Error Response object.
	 */
	public static function rest_fetch_products( $request ) {
		$urls = $request->get_param( 'urls' );

		if ( empty( $urls ) ) {
			return new WP_Error( 'no_urls', __( 'No URLs provided.', 'tools-for-makeshop-wp-option' ), array( 'status' => 400 ) );
		}

		$products = array();
		foreach ( $urls as $url ) {
			if ( empty( $url ) ) {
				continue;
			}

			$product = TFMWP_Makeshop_Scraper::fetch_product( $url, true ); // Force refresh
			if ( ! is_wp_error( $product ) ) {
				$products[] = $product;
			} else {
				// Include error information for failed URLs
				$products[] = array(
					'url'   => $url,
					'error' => $product->get_error_message(),
				);
			}
		}

		return rest_ensure_response(
			array(
				'products'    => $products,
				'lastFetched' => time(),
			)
		);
	}

	/**
	 * Register the block.
	 */
	public static function register_block() {
		// Load asset file generated by wp-scripts.
		$asset_file = include TFMWP_PLUGIN_DIR . 'build/index.asset.php';

		// Register the block using block.json with additional script/style registration.
		register_block_type(
			TFMWP_PLUGIN_DIR . 'build/block.json',
			array(
				'render_callback' => array( __CLASS__, 'render_block' ),
				'editor_script_handles' => array(),
				'editor_style_handles' => array(),
				'style_handles' => array(),
			)
		);

		// Register and enqueue block assets manually.
		wp_register_script(
			'tfmwp-product-display-editor-script',
			TFMWP_PLUGIN_URL . 'build/index.js',
			$asset_file['dependencies'],
			$asset_file['version'],
			true
		);

		wp_register_style(
			'tfmwp-product-display-editor-style',
			TFMWP_PLUGIN_URL . 'build/index.css',
			array( 'wp-edit-blocks' ),
			$asset_file['version']
		);

		wp_register_style(
			'tfmwp-product-display-style',
			TFMWP_PLUGIN_URL . 'build/style-index.css',
			array(),
			$asset_file['version']
		);

		// Enqueue scripts and styles for the block editor.
		add_action( 'enqueue_block_editor_assets', function() {
			wp_enqueue_script( 'tfmwp-product-display-editor-script' );
			wp_enqueue_style( 'tfmwp-product-display-editor-style' );
		} );

		// Enqueue frontend styles.
		add_action( 'enqueue_block_assets', function() {
			if ( ! is_admin() ) {
				wp_enqueue_style( 'tfmwp-product-display-style' );
			}
		} );
	}

	/**
	 * Render the block on the frontend.
	 *
	 * @param array $attributes Block attributes.
	 * @return string Block HTML.
	 */
	public static function render_block( $attributes ) {
		$product_urls = isset( $attributes['productUrls'] ) ? $attributes['productUrls'] : '';
		$columns_desktop = isset( $attributes['columnsDesktop'] ) ? intval( $attributes['columnsDesktop'] ) : 4;
		$columns_tablet = isset( $attributes['columnsTablet'] ) ? intval( $attributes['columnsTablet'] ) : 3;
		$columns_mobile = isset( $attributes['columnsMobile'] ) ? intval( $attributes['columnsMobile'] ) : 2;

		if ( empty( $product_urls ) ) {
			return '';
		}

		// Split URLs by newline and filter empty lines.
		$urls = array_filter( array_map( 'trim', explode( "\n", $product_urls ) ) );

		if ( empty( $urls ) ) {
			return '';
		}

		// Fetch product information for each URL.
		$products = array();
		foreach ( $urls as $url ) {
			$product = TFMWP_Makeshop_Scraper::fetch_product( $url );
			if ( ! is_wp_error( $product ) ) {
				$products[] = $product;
			}
		}

		if ( empty( $products ) ) {
			return '<p>' . esc_html__( 'No products found.', 'tools-for-makeshop-wp-option' ) . '</p>';
		}

		// Build HTML output.
		ob_start();
		?>
		<div class="tfmwp-product-grid" data-columns-desktop="<?php echo esc_attr( $columns_desktop ); ?>" data-columns-tablet="<?php echo esc_attr( $columns_tablet ); ?>" data-columns-mobile="<?php echo esc_attr( $columns_mobile ); ?>">
			<?php foreach ( $products as $product ) : ?>
				<div class="tfmwp-product-item">
					<a href="<?php echo esc_url( $product['url'] ); ?>" class="tfmwp-product-link" target="_blank" rel="noopener">
						<?php if ( ! empty( $product['image'] ) ) : ?>
							<div class="tfmwp-product-image">
								<img src="<?php echo esc_url( $product['image'] ); ?>" alt="<?php echo esc_attr( $product['name'] ); ?>" loading="lazy">
							</div>
						<?php endif; ?>
						<div class="tfmwp-product-info">
							<?php if ( ! empty( $product['category'] ) ) : ?>
								<div class="tfmwp-product-category"><?php echo esc_html( $product['category'] ); ?></div>
							<?php endif; ?>
							<?php if ( ! empty( $product['name'] ) ) : ?>
								<h3 class="tfmwp-product-name"><?php echo esc_html( $product['name'] ); ?></h3>
							<?php endif; ?>
							<?php if ( ! empty( $product['price'] ) ) : ?>
								<div class="tfmwp-product-price"><?php echo esc_html( $product['price'] ); ?></div>
							<?php endif; ?>
							<?php if ( ! empty( $product['description'] ) ) : ?>
								<p class="tfmwp-product-description"><?php echo esc_html( wp_trim_words( $product['description'], 20 ) ); ?></p>
							<?php endif; ?>
						</div>
					</a>
				</div>
			<?php endforeach; ?>
		</div>
		<?php
		return ob_get_clean();
	}
}
